name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tests:
    name: Tests
    env:
      ENV_NAME: bayeslim_tests
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11]
      fail-fast: false

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Get Miniconda (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
        bash $HOME/miniconda.sh -b -p $HOME/miniconda
    - name: Setup Environment
      run: |
        export PATH="$HOME/miniconda/bin:$PATH";
        ./ci/install_conda.sh
    - name: Install
      run: |
        export PATH="$HOME/miniconda/bin:$PATH";
        conda activate ${ENV_NAME};
        pip install .
    - name: Run Tests
      run: |
        export PATH="$HOME/miniconda/bin:$PATH";
        conda activate ${ENV_NAME};
        pytest --cov-report xml:./coverage.xml
    - name: Upload Coverage (Ubuntu)
      if: matrix.os == 'ubuntu-latest' && success()
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
